=== hmrc/individuals-income-received-api/resources/public/api/conf/2.0/schemas/capital_gains_other_retrieve_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Other Capital Gains and Disposals Response",
  "description": "Retrieve Other Capital Gains and Disposals Response",
  "type": "object",
  "properties": {
    "submittedOn": {
      "type": "string",
      "description": "The date the disposals were submitted to the Report and pay Capital Gains Tax on UK property service. It is in the format YYYY-MM-DDThh:mm:ssZ.",
      "example": "2020-07-06T09:37:17Z"
    },
    "disposals": {"$ref": "capital_gains_other_definitions.json#/definitions/disposals"},
    "nonStandardGains": {"$ref": "capital_gains_other_definitions.json#/definitions/nonStandardGains"},
    "losses": {"$ref": "capital_gains_other_definitions.json#/definitions/losses"},
    "adjustments": {"$ref": "capital_gains_other_definitions.json#/definitions/adjustments"},
    "links": {"$ref":  "capital_gains_other_definitions.json#/definitions/links"}
  },
  "required": [
    "submittedOn",
    "links"
  ]
}

=== hmrc/individuals-income-received-api/resources/public/api/conf/2.0/examples/cgt/other/retrieve_response.json
{
  "submittedOn": "2020-07-06T09:37:17.000Z",
  "disposals": [
    {
      "assetType": "otherProperty",
      "assetDescription": "Property Sale",
      "acquisitionDate": "2021-05-01",
      "disposalDate": "2021-06-01",
      "disposalProceeds": 1000.12,
      "allowableCosts": 1000.12,
      "gain": 1000.12,
      "claimOrElectionCodes": [
        "PRR"
      ],
      "gainAfterRelief": 1000.12,
      "rttTaxPaid": 1000.12
    }
  ],
  "nonStandardGains": {
    "carriedInterestGain": 1000.12,
    "carriedInterestRttTaxPaid": 1000.12,
    "attributedGains": 1000.12,
    "attributedGainsRttTaxPaid": 1000.12,
    "otherGains": 1000.12,
    "otherGainsRttTaxPaid": 1000.12
  },
  "losses": {
    "broughtForwardLossesUsedInCurrentYear": 1000.12,
    "setAgainstInYearGains": 1000.12,
    "setAgainstInYearGeneralIncome": 1000.12,
    "setAgainstEarlierYear": 1000.12
  },
  "adjustments": 1000.12,
  "links": [
    {
      "href": "/income-received/disposals/other-gains/AA111111A/2020-21",
      "rel": "create-and-amend-other-capital-gains-and-disposals",
      "method": "PUT"
    },
    {
      "href": "/income-received/disposals/other-gains/AA111111A/2020-21",
      "rel": "delete-other-capital-gains-and-disposals",
      "method": "DELETE"
    },
    {
      "href": "/income-received/disposals/other-gains/AA111111A/2020-21",
      "rel": "self",
      "method": "GET"
    }
  ]
}
