=== hmrc/individuals-income-received-api/resources/public/api/conf/2.0/schemas/foreign_retrieve_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Foreign Income Request",
  "description": "Retrieve Foreign Income Request",
  "type": "object",
  "properties": {
    "submittedOn": {"$ref": "foreign_definitions.json#/definitions/submittedOn"},
    "foreignEarnings": {"$ref": "foreign_definitions.json#/definitions/foreignEarnings"},
    "unremittableForeignIncome": {"$ref": "foreign_definitions.json#/definitions/unremittableForeignIncome"},
    "links": {"$ref": "foreign_definitions.json#/definitions/links"}
  },
  "required": ["submittedOn"]
}

=== hmrc/individuals-income-received-api/resources/public/api/conf/1.0/examples/foreignIncome/retrieve_foreign_response.json
{
  "submittedOn": "2020-07-06T09:37:17Z",
  "foreignEarnings":{
    "customerReference":"FOREIGNINCME123A",
    "earningsNotTaxableUK":1999.99
  },
  "unremittableForeignIncome":[
    {
      "countryCode":"FRA",
      "amountInForeignCurrency":1999.99,
      "amountTaxPaid":1999.99
    },
    {
      "countryCode":"IND",
      "amountInForeignCurrency":2999.99,
      "amountTaxPaid":2999.99
    }
  ],
  "links":[
    {
      "href":"/individuals/income-received/foreign/TC663795B/2021-22",
      "rel":"create-and-amend-foreign-income",
      "method":"PUT"
    },
    {
      "href":"/individuals/income-received/foreign/TC663795B/2021-22",
      "rel":"self",
      "method":"GET"
    },
    {
      "href":"/individuals/income-received/foreign/TC663795B/2021-22",
      "rel":"delete-foreign-income",
      "method":"DELETE"
    }
  ]
}
