=== hmrc/individuals-income-received-api/resources/public/api/conf/1.0/schemas/capital_gains_other_amend_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Create and Amend Other Capital Gains and Disposals Request",
  "description": "Create and Amend Other Capital Gains and Disposals Request",
  "type": "object",
  "properties": {
    "disposals": {"$ref": "capital_gains_other_definitions.json#/definitions/disposals"},
    "nonStandardGains": {"$ref": "capital_gains_other_definitions.json#/definitions/nonStandardGains"},
    "losses": {"$ref": "capital_gains_other_definitions.json#/definitions/losses"},
    "adjustments": {"$ref": "capital_gains_other_definitions.json#/definitions/adjustments"}
  }
}

=== hmrc/individuals-income-received-api/resources/public/api/conf/2.0/examples/cgt/other/amend_request.json
{
  "disposals":[
    {
      "assetType":"otherProperty",
      "assetDescription":"Property Sale",
      "acquisitionDate":"2021-05-01",
      "disposalDate":"2021-06-01",
      "disposalProceeds":1000.12,
      "allowableCosts":1000.12,
      "gain":1000.12,
      "claimOrElectionCodes":[
        "PRR"
      ],
      "gainAfterRelief":1000.12,
      "rttTaxPaid":1000.12
    }
  ],
  "nonStandardGains":{
    "carriedInterestGain":1000.12,
    "carriedInterestRttTaxPaid":1000.12,
    "attributedGains":1000.12,
    "attributedGainsRttTaxPaid":1000.12,
    "otherGains":1000.12,
    "otherGainsRttTaxPaid":1000.12
  },
  "losses":{
    "broughtForwardLossesUsedInCurrentYear":1000.12,
    "setAgainstInYearGains":1000.12,
    "setAgainstInYearGeneralIncome":1000.12,
    "setAgainstEarlierYear":1000.12
  },
  "adjustments":1000.12
}
