=== hmrc/individuals-income-received-api/resources/public/api/conf/1.0/schemas/insurance_amend_request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Amend Insurance Policies Income Request",
  "description": "Amend Insurance Policies Income Request",
  "type": "object",
  "properties": {
    "lifeInsurance": {
      "type": "array",
      "description": "Financial details about life insurance income",
      "items": {"$ref": "insurance_definitions.json#/definitions/commonPolicyObject"}
    },
    "capitalRedemption": {
      "type": "array",
      "description": "Financial details about life capital redemption income",
      "items": {"$ref": "insurance_definitions.json#/definitions/commonPolicyObject"}
    },
    "lifeAnnuity": {
      "type": "array",
      "description": "Financial details about life annuity income",
      "items": {"$ref": "insurance_definitions.json#/definitions/commonPolicyObject"}
    },
    "voidedIsa": {
      "type": "array",
      "description": "Financial details about voided ISA's income",
      "items": {"$ref": "insurance_definitions.json#/definitions/voidedIsaObject"}
    },
    "foreign": {
      "type": "array",
      "description": "Financial details about foreign policies Items income",
      "items": {"$ref": "insurance_definitions.json#/definitions/foreignObject"}
    }
  }
}

=== hmrc/individuals-income-received-api/resources/public/api/conf/1.0/examples/insurancePolicies/amend_insurance_request.json
{
  "lifeInsurance": [
    {
      "customerReference": "INPOLY123A",
      "event": "Policy matured",
      "gainAmount": 1000.23,
      "taxPaid": true,
      "yearsHeld": 10,
      "yearsHeldSinceLastGain": 1,
      "deficiencyRelief": 100.23
    }
  ],
  "capitalRedemption": [
    {
      "customerReference": "INPOLY123B",
      "event": "Policy matured",
      "gainAmount": 1000.23,
      "taxPaid": true,
      "yearsHeld": 10,
      "yearsHeldSinceLastGain": 1,
      "deficiencyRelief": 100.23
    }
  ],
  "lifeAnnuity": [
    {
      "customerReference": "INPOLY123C",
      "event": "Policy matured",
      "gainAmount": 1000.23,
      "taxPaid": true,
      "yearsHeld": 10,
      "yearsHeldSinceLastGain": 1,
      "deficiencyRelief": 100.23
    }
  ],
  "voidedIsa": [
    {
      "customerReference": "INPOLY123D",
      "event": "Policy matured",
      "gainAmount": 1000.23,
      "taxPaidAmount": 100.23,
      "yearsHeld": 10,
      "yearsHeldSinceLastGain": 1
    }
  ],
  "foreign": [
    {
      "customerReference": "INPOLY123E",
      "gainAmount": 1000.23,
      "taxPaidAmount": 100.23,
      "yearsHeld": 10
    }
  ]
}
