=== hmrc/individuals-income-received-api/resources/public/api/conf/1.0/schemas/insurance_retrieve_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Insurance Policies Income Request",
  "description": "Retrieve Insurance Policies Income Request",
  "type": "object",
  "properties": {
    "submittedOn": {"$ref": "insurance_definitions.json#/definitions/submittedOn"},
    "lifeInsurance": {
      "type": "array",
      "description": "Financial details about life insurance income",
      "items": {"$ref": "insurance_definitions.json#/definitions/lifeInsurance"}
    },
    "capitalRedemption": {
      "type": "array",
      "description": "Financial details about life capital redemption income",
      "items": {"$ref": "insurance_definitions.json#/definitions/capitalRedemption"}
    },
    "lifeAnnuity": {
      "type": "array",
      "description": "Financial details about life annuity income",
      "items": {"$ref": "insurance_definitions.json#/definitions/lifeAnnuity"}
    },
    "voidedIsa": {
      "type": "array",
      "description": "Financial details about voided ISA's income",
      "items": {"$ref": "insurance_definitions.json#/definitions/voidedIsaObject"}
    },
    "foreign": {
      "type": "array",
      "description": "Financial details about foreign policies Items income",
      "items": {"$ref": "insurance_definitions.json#/definitions/foreignObject"}
    },
    "links": {"$ref": "insurance_definitions.json#/definitions/links"}
  },
  "required": ["submittedOn"]
}

=== hmrc/individuals-income-received-api/resources/public/api/conf/1.0/examples/insurancePoliciesIncome/retrieve_insurance_response.json
{
  "submittedOn": "2020-07-06T09:37:17Z",
  "lifeInsurance": [
    {
      "customerReference": "INPOLY123A",
      "event": "Policy matured",
      "gainAmount": 1000.23,
      "taxPaid": true,
      "yearsHeld": 10,
      "yearsHeldSinceLastGain": 1,
      "deficiencyRelief": 100.23
    }
  ],
  "capitalRedemption": [
    {
      "customerReference": "INPOLY123B",
      "event": "Policy matured",
      "gainAmount": 1000.23,
      "taxPaid": true,
      "yearsHeld": 10,
      "yearsHeldSinceLastGain": 1,
      "deficiencyRelief": 100.23
    }
  ],
  "lifeAnnuity": [
    {
      "customerReference": "INPOLY123C",
      "event": "Policy matured",
      "gainAmount": 1000.23,
      "taxPaid": true,
      "yearsHeld": 10,
      "yearsHeldSinceLastGain": 1,
      "deficiencyRelief": 100.23
    }
  ],
  "voidedIsa": [
    {
      "customerReference": "INPOLY123D",
      "event": "Policy matured",
      "gainAmount": 1000.23,
      "taxPaidAmount": 100.23,
      "yearsHeld": 10,
      "yearsHeldSinceLastGain": 1
    }
  ],
  "foreign": [
    {
      "customerReference": "INPOLY123E",
      "gainAmount": 1000.23,
      "taxPaidAmount": 100.23,
      "yearsHeld": 10
    }
  ],
  "links": [
    {
      "href": "/individuals/income-received/insurance-policies/TC663795B/2021-22",
      "rel": "create-and-amend-insurance-policies-income",
      "method": "PUT"
    },
    {
      "href": "/individuals/income-received/insurance-policies/TC663795B/2021-22",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "/individuals/income-received/insurance-policies/TC663795B/2021-22",
      "rel": "delete-insurance-policies-income",
      "method": "DELETE"
    }
  ]
}
