=== hmrc/individuals-income-received-api/resources/public/api/conf/1.0/schemas/pensions_retrieve_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Pensions Income Response",
  "description": "Retrieve Pensions Income Response",
  "type": "object",
  "properties": {
    "submittedOn": {"$ref": "pensions_definitions.json#/definitions/submittedOn"},
    "foreignPensions": {"$ref": "pensions_definitions.json#/definitions/foreignPensions"},
    "overseasPensionContributions": {"$ref": "pensions_definitions.json#/definitions/overseasPensionContributions"},
    "links": {"$ref": "pensions_definitions.json#/definitions/links"}
  },
  "required": ["submittedOn"]
}

=== hmrc/individuals-income-received-api/resources/public/api/conf/1.0/examples/pensionsIncome/retrieve_response.json
{
  "submittedOn": "2020-07-06T09:37:17Z",
  "foreignPensions": [
    {
      "countryCode": "FRA",
      "amountBeforeTax": 1999.99,
      "taxTakenOff": 1999.99,
      "specialWithholdingTax": 1999.99,
      "foreignTaxCreditRelief": false,
      "taxableAmount": 1999.99
    }
  ],
  "overseasPensionContributions": [
    {
      "customerReference": "PENSIONINCOME245",
      "exemptEmployersPensionContribs": 1999.99,
      "migrantMemReliefQopsRefNo": "QOPS000000",
      "dblTaxationRelief": 1999.99,
      "dblTaxationCountryCode": "FRA",
      "dblTaxationArticle": "AB3211-1",
      "dblTaxationTreaty": "MUNICH",
      "sf74reference": "SF74-123456"
    }
  ],
  "links":[
    {
      "href":"/individuals/income-received/pensions/TC663795B/2021-22",
      "rel":"create-and-amend-pensions-income",
      "method":"PUT"
    },
    {
      "href":"/individuals/income-received/pensions/TC663795B/2021-22",
      "rel":"self",
      "method":"GET"
    },
    {
      "href":"/individuals/income-received/pensions/TC663795B/2021-22",
      "rel":"delete-pensions-income",
      "method":"DELETE"
    }
  ]
}
