=== hmrc/individuals-income-received-api/resources/public/api/conf/1.0/schemas/savings_retrieve_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Retrieve Savings Income Request",
  "description": "Retrieve Savings Income Request",
  "type": "object",
  "properties": {
    "submittedOn": {"$ref": "savings_definitions.json#/definitions/submittedOn"},
    "securities": {"$ref": "savings_definitions.json#/definitions/securities"},
    "foreignInterest": {"$ref": "savings_definitions.json#/definitions/foreignInterest"},
    "links": {"$ref": "savings_definitions.json#/definitions/links"}
  },
  "required": ["submittedOn"]
}

=== hmrc/individuals-income-received-api/resources/public/api/conf/1.0/examples/savingsIncome/retrieve_savings_response.json
{
  "submittedOn": "2020-07-06T09:37:17Z",
  "securities": {
    "taxTakenOff": 100.12,
    "grossAmount": 1455.23,
    "netAmount": 1355.11
  },
  "foreignInterest": [
    {
      "amountBeforeTax": 1232.67,
      "countryCode": "DEU",
      "taxTakenOff": 12.45,
      "specialWithholdingTax": 14.78,
      "taxableAmount": 1032.67,
      "foreignTaxCreditRelief": true
    }
  ],
  "links":[
    {
      "href":"/individuals/income-received/savings/TC663795B/2021-22",
      "rel":"create-and-amend-savings-income",
      "method":"PUT"
    },
    {
      "href":"/individuals/income-received/savings/TC663795B/2021-22",
      "rel":"self",
      "method":"GET"
    },
    {
      "href":"/individuals/income-received/savings/TC663795B/2021-22",
      "rel":"delete-savings-income",
      "method":"DELETE"
    }
  ]
}

=== hmrc/individuals-income-received-api/resources/public/api/conf/2.0/examples/savingsIncome/retrieve_savings_response.json
{
  "submittedOn": "2021-04-06T09:37:17.000Z",
  "securities": {
    "taxTakenOff": 100.12,
    "grossAmount": 1455.23,
    "netAmount": 1355.11
  },
  "foreignInterest": [
    {
      "countryCode": "DEU",
      "amountBeforeTax": 1232.67,
      "taxTakenOff": 12.45,
      "specialWithholdingTax": 14.78,
      "foreignTaxCreditRelief": true,
      "taxableAmount": 1032.67
    }
  ],
  "links":[
    {
      "href":"/individuals/income-received/savings/TC663795B/2021-22",
      "rel":"create-and-amend-savings-income",
      "method":"PUT"
    },
    {
      "href":"/individuals/income-received/savings/TC663795B/2021-22",
      "rel":"self",
      "method":"GET"
    },
    {
      "href":"/individuals/income-received/savings/TC663795B/2021-22",
      "rel":"delete-savings-income",
      "method":"DELETE"
    }
  ]
}
